[formatting]
column_width = 120
array_auto_expand = true
allowed_blank_lines = 1

[[rule]]
keys = [
  "build-dependencies",
  "dependencies",
  "dev-dependencies",
  "lints.clippy",
  "patch",
  "toolchain",
  "workspace.dependencies",
  "workspace.lints.clippy",
]

[rule.formatting]
reorder_keys = true
